# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:53
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0002_blog_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '\u4f5c\u8005'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_time'], 'verbose_name': '\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e'},
        ),
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.TextField(default=django.utils.timezone.now, help_text='\u6587\u7ae0\u7684\u6458\u8981', verbose_name='\u6458\u8981'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='pen_name',
            field=models.CharField(help_text='\u4f5c\u8005\u7684\u7b14\u540d\uff08\u663e\u793a\u7684\u4f5c\u8005\u540d\uff09', max_length=30, verbose_name='\u7b14\u540d'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(help_text='\u4f5c\u8005\u5173\u8054\u7684\u7cfb\u7edf\u8d26\u53f7', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7'),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text='\u4f5c\u8005\u7684\u4e2a\u4eba\u4e3b\u9875\u94fe\u63a5', verbose_name='\u4e3b\u9875'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(help_text='\u6587\u7ae0\u7684\u4f5c\u8005', on_delete=django.db.models.deletion.CASCADE, to='sblog.Author', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='caption',
            field=models.CharField(help_text='\u6587\u7ae0\u7684\u6807\u9898', max_length=50, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(help_text='\u6587\u7ae0\u7684\u5206\u7c7b', on_delete=django.db.models.deletion.CASCADE, to='sblog.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='\u6587\u7ae0\u7684\u5185\u5bb9', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(help_text='\u6587\u7ae0\u7684\u5c01\u9762\u56fe\u7247', upload_to='uploads/%Y/%m/%d', verbose_name='\u5c01\u9762'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, help_text='\u6587\u7ae0\u7684\u53d1\u5e03\u65f6\u95f4', verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='\u6587\u7ae0\u7684\u6807\u7b7e', to='sblog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='\u6587\u7ae0\u7684\u66f4\u65b0\u65f6\u95f4', verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='\u5206\u7c7b\u7684\u540d\u79f0', max_length=20, verbose_name='\u5206\u7c7b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(blank=True, help_text='\u6807\u7b7e\u7684\u540d\u79f0', max_length=20, verbose_name='\u540d\u79f0'),
        ),
    ]
