# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0003_auto_20170218_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-stick', '-publish_time'], 'verbose_name': '\u6587\u7ae0'},
        ),
        migrations.AddField(
            model_name='blog',
            name='stick',
            field=models.BooleanField(default=False, help_text='\u6587\u7ae0\u7684\u662f\u5426\u7f6e\u9876', verbose_name='\u7f6e\u9876'),
        ),
        migrations.AddField(
            model_name='blog',
            name='visits',
            field=models.BigIntegerField(default=0, help_text='\u6587\u7ae0\u7684\u6d4f\u89c8\u91cf', verbose_name='\u6d4f\u89c8\u91cf'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='\u6587\u7ae0\u7684\u5185\u5bb9', verbose_name='\u5185\u5bb9'),
        ),
    ]
