# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0004_auto_20170219_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='\u7167\u7247', upload_to='uploads/%Y/%m/%d', verbose_name='\u7167\u7247')),
                ('remark', models.TextField(help_text='\u7167\u7247\u5907\u6ce8', verbose_name='\u5907\u6ce8')),
                ('publish_time', models.DateTimeField(auto_now_add=True, help_text='\u7167\u7247\u7684\u53d1\u5e03\u65f6\u95f4', verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('public', models.BooleanField(default=True, help_text='\u7167\u7247\u662f\u5426\u516c\u5f00', verbose_name='\u516c\u5f00')),
            ],
            options={
                'ordering': ['-publish_time'],
                'verbose_name': '\u76f8\u518c',
            },
        ),
        migrations.CreateModel(
            name='Constanter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_key', models.CharField(help_text='\u5e38\u4eae\u7684\u952e', max_length=50, unique=True, verbose_name='\u952e')),
                ('the_value', models.CharField(help_text='\u5e38\u4eae\u7684\u503c', max_length=200, verbose_name='\u503c')),
                ('descriptions', models.TextField(help_text='\u5e38\u4eae\u7684\u63cf\u8ff0', verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5e38\u91cf',
            },
        ),
    ]
