# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0006_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.CharField(help_text='\u5206\u7c7b\u7684\u7f29\u5199', max_length=20, unique=True, verbose_name='\u5206\u7c7b\u7f29\u5199'),
        ),
    ]
